--- 
title: "Biology 116 Lab Manual"
author: "Dr. Tristyn Hay and Dr. Robin Young"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "Biology lab manual for BIOL 116 at the UBC Okanagan Campus"
---

# Welcome {-}

Welcome to the BIOL116 lab manual!

The material in this manual is designed to be used as part of the BIOL116 labs. It integrates heavily with additional material that can be accessed only through the [BIOL116 Canvas page](https://canvas.ubc.ca/courses/94572), including assignments, quizzes, and other material that is specific to this year\'s offering of the course. As such you will be expected to access BOTH this website and Canvas regularly.

**Your first lab**, Lab 1, is online and requires you to be in your zoom rooms during your regular scheduled times. **Your second lab**, Lab 2, will be your first chance to physically enter the lab, and meet your TA and your fellow lab mates. The material for Lab 2 can be found in this text, under the [Lab 2A](https://ubco-biology.github.io/BIOL-116-Lab-Manual/the-process-of-science.html) and [Lab2B](https://ubco-biology.github.io/BIOL-116-Lab-Manual/research-project.html) headings (with links to this content also on Canvas).

The rest of the labs will continue alternating between online and on campus. For all labs you must attend during your regular scheduled lab times regardless of whether its online or on campus. **For in-person labs it is vital that you attend the lab in which you are registered** (Check your registration online to be sure of where you are supposed to be!).

There\'s much more information about what to expect from labs, the grading policies, and the weekly schedule in the [Canvas shell for BIOL 116 labs](https://canvas.ubc.ca). For now, we will say that we\'re looking forward to the start of term, and to meeting you (both virtually and in-person). Science is amazing and exciting and cool, and we can\'t wait to share our love of science and biology with you!

## Learning Objectives {-}

In BIOL116, we use lecture primarily to teach course content, and lab to teach fundamental skills. The learning goals below highlight some of the skills we are expecting you to develop throughout BIOL116. All of them will be addressed in lab, and some will also show up in how we approach content in lecture as well.

**Learning Goals about the Process of Science**

- Explain how scientists use inference and evidence-based reasoning to generate knowledge
- Describe the iterative nature of science and how new evidence can lead to the revision of knowledge 
- Compare the strengths and weaknesses of different types of experimental design.
- Explain the importance of understanding science, and the relevance of science in everyday experiences.
- Design a controlled experiment, including plans for analyzing the data and interpretation of the results.
- Find and evaluate the credibility of a variety of sources, of scientific information, including popular science, media and scientific journals.
- Make evidence-based arguments using your own results, and the scientific literature.
- Identify the basic principles of Open Science, and apply them to your own research.

**Learning Goals about Communication & Collaboration**

- Use appropriate language and style to communicate science effectively to a targeted audience (e.g., general public versus biology experts).
- Work effectively with teammates to design experiments, analyze results & communicate findings.

## Copyright {-}

This work is licenced under the Creative Commons [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Note** some content in this work has been reproduced with permission from the original creators. To further reproduce these sections, please contact the original creators directly for permission.

Please use the following for citing this document

Hay, T., Young, R. (2021). *Biology 116 Lab Manual*. [https://ubco-biology.github.io/BIOL-116-Lab-Manual/](https://ubco-biology.github.io/BIOL-116-Lab-Manual/)

All source files are available from [https://github.com/ubco-biology/BIOL-116-Lab-Manual](https://github.com/ubco-biology/BIOL-116-Lab-Manual).

## UBCO Biology open materials {-}

This resource is part of a larger project to host UBCO Biology lab materials in an open, accessible format.

All BIOL open materials can be found at [https://ubco-biology.github.io/](https://ubco-biology.github.io/)

## Conventions {-}

<div class = "note">
Further insights or notes on presented materials.
</div>

<div class = "advanced">
Optional material that dives deeper into a presented concept.
</div>
